In [1]:
import pandas as pd 
df = pd.read_csv("Airbnb_Open_Data.csv")
df.head()

C:\Users\MEHUL\AppData\Local\Temp\ipykernel_3048\1864760091.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [2]:
df['house_rules'] = df['house_rules'].fillna("None do whatever you want")

In [3]:
newnm = [' Clean & quiet apt home by the park,Skylit Midtown Castle','THE VILLAGE OF HARLEM....NEW YORK !','Entire Apt: Spacious Studio/Loft by central park','Spare room in Williamsburg','Best Location near Columbia U','Comfy','bright room in Brooklyn','Big Studio-One Stop from Midtown','585 sf Luxury Studio']

In [4]:
import numpy as np 
df['NAME'] = df['NAME'].replace('nan','np.nan')
df['NAME'] = df['NAME'].apply(lambda x:np.random.choice(newnm) if pd.isnull(x) else x).str.title()
df['NAME'].isnull().sum()

np.int64(0)

In [5]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & Quiet Apt Home By The Park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,The Village Of Harlem....New York !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,Big Studio-One Stop From Midtown,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,None do whatever you want,NaN
4,1003689,Entire Apt: Spacious Studio/Loft By Central Park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare Room In Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location Near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, Bright Room In Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,None do whatever you want,NaN
102597,6094094,Big Studio-One Stop From Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,None do whatever you want,NaN
102598,6094647,585 Sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,None do whatever you want,NaN

In [6]:
emptvalue = ['verified','uncomfirmed']

df['host_identity_verified'] = df['host_identity_verified'].apply(lambda x: np.random.choice(emptvalue) if pd.isnull(x) else x)
df['host_identity_verified'].isnull().sum()
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & Quiet Apt Home By The Park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,The Village Of Harlem....New York !,78829239556,verified,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,Big Studio-One Stop From Midtown,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,None do whatever you want,NaN
4,1003689,Entire Apt: Spacious Studio/Loft By Central Park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare Room In Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location Near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, Bright Room In Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,None do whatever you want,NaN
102597,6094094,Big Studio-One Stop From Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,None do whatever you want,NaN
102598,6094647,585 Sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,None do whatever you want,NaN

In [7]:
# df.head(20)
df.drop('country code',axis=1,inplace=True)

In [8]:
x1 = ['Madaline','Jenna','Elise','Garry','Lyndon','Michelle','Alberta','Emma','Evelyn','Carl','Miranda','Alan','Darcy','Leonardo','Daniel','Heather','Ryan','Alberta','Martin']
# print(x1)
df['host name'] = df['host name'].apply(lambda x: np.random.choice(x1) if pd.isnull(x) else x)

df.head(20)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & Quiet Apt Home By The Park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,The Village Of Harlem....New York !,78829239556,verified,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,Big Studio-One Stop From Midtown,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,None do whatever you want,NaN
4,1003689,Entire Apt: Spacious Studio/Loft By Central Park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 Br Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,Blissartsspace!,61300605564,uncomfirmed,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,Blissartsspace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'Way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN
10,1006859,Cute & Cozy Lower East Side 1 Bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,None do whatever you want,NaN
11,1007411,Beautiful 1Br On Upper West Side,18824631834,verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,...,$121,5.0,53.0,6/22/2019,0.43,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",NaN
12,1007964,Central Manhattan/Near Broadway,88136055909,verified,Miranda,Manhattan,Hell's Kitchen,40.76076,-73.98867,United States,...,$143,2.0,188.0,6/23/2019,1.50,4.0,1.0,258.0,- One of the bedroom closets is not accessible...,NaN
13,1008516,"Lovely Room 1, Garden, Best Area, Legal Rental",26802410424,verified,Darcy,brookln,South Slope,40.66829,-73.98779,United States,...,$116,4.0,167.0,6/24/2019,1.34,4.0,3.0,47.0,None do whatever you want,NaN
14,1009068,Wonderful Guest Bedroom In Manhattan For Singles,88920244552,verified,Leonardo,Manhattan,Upper West Side,40.79826,-73.96113,United States,...,$30,2.0,113.0,7/5/2019,0.91,3.0,1.0,68.0,None do whatever you want,NaN
15,1009621,West Village Nest - Superhost,46551725984,verified,Daniel,Manhattan,West Village,40.73530,-74.00525,United States,...,NaN,90.0,27.0,10/31/2018,0.22,3.0,1.0,100.0,Arrival time can be no later than 9:00PM unles...,NaN
16,1010173,Only 2 Stops To Manhattan Studio,62566345680,unconfirmed,Heather,Brooklyn,Williamsburg,40.70837,-73.95352,United States,...,NaN,2.0,148.0,6/29/2019,1.20,3.0,1.0,197.0,"Absolutely no smoking in the building, handlin...",NaN
17,1010725,Perfect For Your Parents + Garden,80380130347,verified,Ryan,Brooklyn,Fort Greene,40.69169,-73.97185,United States,...,NaN,2.0,198.0,6/28/2019,1.72,5.0,1.0,96.0,"- Please be mindful of the neighbors, quiet ti...",NaN
18,1011277,Chelsea Perfect,73862528370,verified,Alberta,manhatan,Chelsea,40.74192,-73.99501,United States,...,NaN,1.0,260.0,7/1/2019,2.12,3.0,1.0,325.0,None do whatever you want,NaN
19,1011830,Hip Historic Brownstone Apartment With Backyard,72145018858,uncomfirmed,Martin,Brooklyn,Crown Heights,40.67592,-73.94694,United States,...,NaN,3.0,53.0,6/22/2019,4.44,5.0,1.0,345.0,LAUNDRY - Laundry can be done by the visitor b...,NaN

In [9]:
df.isnull().sum()

id                                     0
NAME                                   0
host id                                0
host_identity_verified                 0
host name                              0
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                            0
license                           102597
dtype: int64

In [10]:
df.drop('neighbourhood group',axis=1,inplace=True)

In [11]:
neighbourhood_list = [
    'Kensington',
    'Midtown',
    'Harlem',
    'Clinton Hill',
    'East Harlem',
    'Murray Hill',
    'Bedford-Stuyvesant',
    "Hell's Kitchen",
    'Upper West Side',
    'Chinatown',
    'South Slope',
    'West Village',
    'Williamsburg',
    'Fort Greene',
    'Chelsea',
    'Crown Heights',
    'Park Slope',
    'Windsor Terrace',
    'Inwood',
    'East Village'
]

In [12]:
df['neighbourhood'] = df['neighbourhood'].apply(lambda x: np.random.choice(neighbourhood_list) if pd.isnull(x) else x)

In [13]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood,lat,long,country,instant_bookable,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & Quiet Apt Home By The Park,80014485718,unconfirmed,Madaline,Kensington,40.64749,-73.97237,United States,False,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Midtown,40.75362,-73.98377,United States,False,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,The Village Of Harlem....New York !,78829239556,verified,Elise,Harlem,40.80902,-73.94190,United States,True,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,Big Studio-One Stop From Midtown,85098326012,unconfirmed,Garry,Clinton Hill,40.68514,-73.95976,United States,True,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,None do whatever you want,NaN
4,1003689,Entire Apt: Spacious Studio/Loft By Central Park,92037596077,verified,Lyndon,East Harlem,40.79851,-73.94399,United States,False,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare Room In Williamsburg,12312296767,verified,Krik,Williamsburg,40.70862,-73.94651,United States,False,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location Near Columbia U,77864383453,unconfirmed,Mifan,Morningside Heights,40.80460,-73.96545,United States,True,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, Bright Room In Brooklyn",69050334417,unconfirmed,Megan,Park Slope,40.67505,-73.98045,United States,True,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,None do whatever you want,NaN
102597,6094094,Big Studio-One Stop From Midtown,11160591270,unconfirmed,Christopher,Long Island City,40.74989,-73.93777,United States,True,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,None do whatever you want,NaN
102598,6094647,585 Sf Luxury Studio,68170633372,unconfirmed,Rebecca,Upper West Side,40.76807,-73.98342,United States,False,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,None do whatever you want,NaN

In [15]:
df.drop('host id',axis=1,inplace=True)

In [16]:
df.drop('minimum nights',axis=1,inplace=True)

In [17]:
df.drop('reviews per month',axis=1,inplace=True)

In [18]:
df.isnull().sum()

id                                     0
NAME                                   0
host_identity_verified                 0
host name                              0
neighbourhood                          0
lat                                    8
long                                   8
country                              532
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
number of reviews                    183
last review                        15893
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                            0
license                           102597
dtype: int64

In [19]:
df['country'] = df['country'].fillna('United States')

In [20]:
s1 = ['TRUE','FALSE']
df['instant_bookable'] = df['instant_bookable'].apply(lambda x: np.random.choice(s1) if pd.isnull(x) else x)

In [22]:
# df['cancellation_policy']
st = ['strict','moderate','flexible']
df['instant_bookable'] = df['instant_bookable'].apply(lambda x: np.random.choice(s1) if pd.isnull(x) else x)

In [23]:
# df['Construction year'].max()
# df['Construction year'].min()

x1=[2022,2012,2004,2005,2006,2007,2010,2020,2021,2019,2015]
df['Construction year'] = df['Construction year'].apply(lambda x: np.random.choice(x1) if pd.isnull(x) else x)

In [25]:
df['price'] = pd.to_numeric(df['price'].replace('[\$,]','',regex=True))
df['price']
df['price'] = df['price'].fillna(df['price'].mean()).astype(int)
df['price'].isnull().sum()
df['price'] = '$' + df['price'].astype(str)
df['price']

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\MEHUL\AppData\Local\Temp\ipykernel_3048\3231069412.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['price'] = pd.to_numeric(df['price'].replace('[\$,]','',regex=True))

0          $966
1          $142
2          $620
3          $368
4          $204
          ...
102594     $844
102595     $837
102596     $988
102597     $546
102598    $1032
Name: price, Length: 102599, dtype: object

In [26]:
df['service fee'].head(20)

0     $193
1      $28
2     $124
3      $74
4      $41
5     $115
6      $14
7     $212
8     $204
9      $58
10     $64
11    $121
12    $143
13    $116
14     $30
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
Name: service fee, dtype: object

In [27]:
df['service fee'] = pd.to_numeric(df['service fee'].replace('[\$,]','',regex=True))
df['service fee'] = df['service fee'].fillna(df['service fee'].mean()).astype(int)
# df['service fee'].isnull().sum()
df['service fee'] = '$' + df['service fee'].astype(str)
df['service fee'].head(20)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\MEHUL\AppData\Local\Temp\ipykernel_3048\2229584007.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['service fee'] = pd.to_numeric(df['service fee'].replace('[\$,]','',regex=True))

0     $193
1      $28
2     $124
3      $74
4      $41
5     $115
6      $14
7     $212
8     $204
9      $58
10     $64
11    $121
12    $143
13    $116
14     $30
15    $125
16    $125
17    $125
18    $125
19    $125
Name: service fee, dtype: object

In [28]:
df['number of reviews'] = df['number of reviews'].fillna(df['number of reviews'].mean()).astype(int)

In [29]:
df['number of reviews']

0           9
1          45
2           0
3         270
4           9
         ...
102594      0
102595      1
102596      0
102597      5
102598      0
Name: number of reviews, Length: 102599, dtype: int64

In [30]:
df.drop('last review',axis=1,inplace=True)

In [31]:
sd = [1,2,3,4,5]
df['review rate number'] = df['review rate number'].apply(lambda x: np.random.choice(sd) if pd.isnull(x) else x).astype(int)

In [32]:
df['review rate number']

0         4
1         4
2         5
3         4
4         3
         ..
102594    3
102595    2
102596    5
102597    3
102598    3
Name: review rate number, Length: 102599, dtype: int64

In [33]:
df.isnull().sum()

id                                     0
NAME                                   0
host_identity_verified                 0
host name                              0
neighbourhood                          0
lat                                    8
long                                   8
country                                0
instant_bookable                       0
cancellation_policy                   76
room type                              0
Construction year                      0
price                                  0
service fee                            0
number of reviews                      0
review rate number                     0
calculated host listings count       319
availability 365                     448
house_rules                            0
license                           102597
dtype: int64

In [34]:
df['house_rules'].isnull().sum()

np.int64(0)

In [35]:
df.drop('license',axis=1,inplace=True)

In [39]:
s1=['strict''moderate','flexible']

df['cancellation_policy'] = df['cancellation_policy'].apply(lambda x: np.random.choice(s1) if pd.isnull(x) else x)

In [40]:
df.isnull().sum()

id                                  0
NAME                                0
host_identity_verified              0
host name                           0
neighbourhood                       0
lat                                 8
long                                8
country                             0
instant_bookable                    0
cancellation_policy                 0
room type                           0
Construction year                   0
price                               0
service fee                         0
number of reviews                   0
review rate number                  0
calculated host listings count    319
availability 365                  448
house_rules                         0
dtype: int64

In [42]:
df.drop('id',axis=1,inplace=True)

In [43]:
df.drop('host_identity_verified',axis=1,inplace=True)

In [45]:
df['calculated host listings count'].min()
df['calculated host listings count'].max()

np.float64(332.0)

In [46]:
x1 = [12, 295, 88, 174, 39, 301, 242, 151, 213, 119, 275, 90, 201, 265, 60, 143, 248, 37, 106, 223,
 178, 52, 5, 128, 194, 292, 310, 269, 203, 16, 84, 136, 70, 145, 160, 19, 286, 102, 309, 32,
 290, 211, 221, 97, 230, 185, 304, 206, 123, 56]

df['calculated host listings count'] = df['calculated host listings count'].apply(lambda x: np.random.choice(x1) if pd.isnull(x) else x)

In [48]:
df['availability 365'].max()

np.float64(3677.0)

In [51]:
# df.drop('NAME',axis=1,inplace=True)
df.drop('host name',axis=1,inplace=True)

In [50]:
df.isnull().sum()

host name                           0
neighbourhood                       0
lat                                 8
long                                8
country                             0
instant_bookable                    0
cancellation_policy                 0
room type                           0
Construction year                   0
price                               0
service fee                         0
number of reviews                   0
review rate number                  0
calculated host listings count      0
availability 365                  448
house_rules                         0
dtype: int64

In [52]:
df.to_csv('Cleaned_dataset_airbnb.csv',index=False)